services:
  database:
    image: "postgres"
    environment:
      PGUSER: postgres
      PGPASSWORD: postgres
      PGDATABASE: postgres
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
#    env_file:
#      - database.env
    volumes:
      - database-data:/var/lib/postgresql/data/
    ports:
      - "5431:5432"
    expose:
      - "5431"

volumes:
  database-data: